<a href="https://colab.research.google.com/github/KanayaDzikra/Pemograman-dasar/blob/main/program_matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🖥️👩🏻‍💻PRAKTIKUM PEMROGRAMAN LANJUT🔥**
##**Pertemuan (3) MATRIKS (STRUKTUR) - Senin, 09 Desember 2024**

👤 Nama: Kanaya Dzikra Setiadi / NRP: 2C2230015 / Kelas: III/A Sains Data

💬Deskripsi Pembahasan Materi Matriks:

1.1.  Definisi Matriks () 🔂
- Sekumpulan informasi yang setiap individu elemennya terdefinisi berdasarkan dua buah indeks (yang biasanya dikonotasikan dengan baris dan kolom)

- Setiap elemen matriks dapat diakses secara langsung jika kedua indeks diketahui.

- Setiap elemen matriks mempunyai type yang homogen

- Matriks adalah struktur data dengan memori internal. Struktur ini praktis untuk dipakai tetapi memakan memori!

- Matriks integer 100 x 100 memakan 10000 x tempat penyimpanan integer.

1.2. Contoh Pemakaian

• Operasi “biasa” matriks dalam matematika : penjumlahan, perkalian, menentukan determinan, menginvers sebuah matriks, transpose, dll.

• Semua "perhitungan" itu menjadi tidak primitif, harus diprogram

  - Sistem persamaan linier dan operational research

• Persoalan algoritmik: untuk menyimpan informasi yang cirinya ditentukan oleh 2 dimensi (diterjemahkan dalam baris dan kolom).
  
  - Contoh: cell pada sebuah spreadsheet, ruangan gedung bertingkat




#🤸🏻‍♀️ EKSPLORASI PRIBADI DI KELAS ✨

In [2]:
A = [[0 for j in range(20)]for i in range(10)]
print (A)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


- Interpretasi coding:

- Interpretasi Hasil:

In [3]:
n = int(input())
m = int(input())

A = [[0 for j in range(m)]for i in range(n)]

for i in range(n):
  for j in range(m):
    A[i][j] = int(input("Masukkan elemen baris"+str(i+1)+"kolom"+str(j+1)+":"))

for i in range(n):
  for j in range(m):
    print(A[i][j],end=" ")
  print()

3
3
Masukkan elemen baris1kolom1:1
Masukkan elemen baris1kolom2:2
Masukkan elemen baris1kolom3:3
Masukkan elemen baris2kolom1:4
Masukkan elemen baris2kolom2:5
Masukkan elemen baris2kolom3:6
Masukkan elemen baris3kolom1:7
Masukkan elemen baris3kolom2:8
Masukkan elemen baris3kolom3:9
1 2 3 
4 5 6 
7 8 9 


- Interpretasi coding : karna masukan 3 dan 3 makan kolomnya bereskan dulu sampai 3 baru baris kedua sampai kolom ke 3 kemudian baris ketiga sampai kolom ke 3

In [4]:
#matriks dengan array
import numpy as np

x1 = np.array([[2,3,4],[2,5,6],[6,7,8]])
x1

array([[2, 3, 4],
       [2, 5, 6],
       [6, 7, 8]])

Interpretasi :

In [5]:
#matriks dengan list
ls = [[2,3,4],
      [2,5,6],
      [6,7,8]]
ls

[[2, 3, 4], [2, 5, 6], [6, 7, 8]]

In [7]:
x2 = np.dot(x1,x1)
x2

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

- Interpretasi coding : menggunakan library numpy dimana dot dengan kita mengalikan matriks x1 dengan x1

#🧠 LATIHAN SOAL DI KELAS ⏱️

Problem (1) Segitiga Paskal

In [8]:
n = 5

segitiga = [[1] * (i + 1) for i in range(n)]

for i in range(2, n):
    for j in range(1, i):
        segitiga[i][j] = segitiga[i - 1][j - 1] + segitiga[i - 1][j]

for baris in segitiga:
    print(baris)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


**- Interpretasi coding:**

Baris pertama hanya memiliki  1 .

Baris kedua memiliki  1, 1 .

Setiap elemen di baris berikutnya dihitung dengan menjumlahkan dua elemen di atasnya (kiri dan kanan).


**- Interpretasi Hasil:** Segitiga Pascal dalam bentuk list

Problem (2) Linear Algebra

In [9]:
#Bagian A

import numpy as np

# Matriks A
A = np.array([[1, 2], [3, 4]])
det_A = round(np.linalg.det(A))
print("Determinan Matriks A:", det_A)

# Matriks B
B = np.array([[-1, 3, 0], [2, 1, -5], [1, 4, -2]])
det_B = round(np.linalg.det(B))
print("Determinan Matriks B:", det_B)

Determinan Matriks A: -2
Determinan Matriks B: -21


In [10]:
#Bagian B
# Matriks C
print("\nMatriks C:")
C = np.array([
    [1, 3, 7, 2],
    [5, 8, -9, 0],
    [6, -7, 11, 12]
])
print(C)

# Perhitungan Transpose Matriks C
print("\nLangkah-langkah menghitung transpose Matriks C:")
transpose_C = np.transpose(C)
for i in range(C.shape[1]):
    row = [C[j][i] for j in range(C.shape[0])]
    print(f"Kolom {i + 1} dari Matriks C menjadi Baris {i + 1} di Transpose: {row}")

print("\nTranspose Matriks C:")
print(transpose_C)


Matriks C:
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]

Langkah-langkah menghitung transpose Matriks C:
Kolom 1 dari Matriks C menjadi Baris 1 di Transpose: [1, 5, 6]
Kolom 2 dari Matriks C menjadi Baris 2 di Transpose: [3, 8, -7]
Kolom 3 dari Matriks C menjadi Baris 3 di Transpose: [7, -9, 11]
Kolom 4 dari Matriks C menjadi Baris 4 di Transpose: [2, 0, 12]

Transpose Matriks C:
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


**- Interpretasi coding:**

1. Determinant Matriks A (2x2):

•Rumus:  \text{det}(A) = a \cdot d - b \cdot c

•Dicetak langkah-langkah perhitungan secara manual.

2. Determinant Matriks B (3x3):

•Menggunakan ekspansi kofaktor:

{det}(B) = b_{11}(det minor 1) - b_{12}(det minor 2) + b_{13}(det minor 3)

•Perhitungan manual untuk minor matriks.

3. Transpose Matriks:

•Fungsi transpose adalah mengubah baris menjadi kolom.

•Dicetak hasil akhir matriks setelah transpose

**- Interpretasi Hasil:**

- Hasil perhitungan determinan matriks A yaitu -2

- Hasil perhitungan determinan matriks B yaitu -21

-  Hasil perhitungan tranpose matriks C

#🏆 POST TEST 🎯

Problem (1)

- Interpretasi coding:
- Interpretasi hasil: